### ISSUE TITLE
0.8.5 is a "breaking change"

### ISSUE THREAD

**Issue by ForsakenHarmony** [servo/string-cache#271]
```rs
error[E0283]: type annotations needed
  --> {.. snip ..}\browserslist-rs-0.12.3\src\data\caniuse.rs:91:35
   |
91 |     let chrome = CANIUSE_BROWSERS.get(&"chrome".into()).unwrap();
   |                                   ^^^ ---------------- type must be known at this point
   |                                   |
   |                                   cannot infer type of the type parameter `Q` declared on the associated function `get`
   |
   = note: multiple `impl`s satisfying `Atom<BrowserNameAtomStaticSet>: Borrow<_>` found in the following crates: `core`, `string_cache`:
           - impl<Static> Borrow<str> for Atom<Static>
             where Static: StaticAtomSet;
           - impl<T> Borrow<T> for T
             where T: ?Sized;
note: required by a bound in `AHashMap::<K, V, S>::get`
  --> {.. snip ..}\ahash-0.7.6\src\hash_map.rs:81:12
   |
81 |         K: Borrow<Q>,
   |            ^^^^^^^^^ required by this bound in `AHashMap::<K, V, S>::get`
help: consider specifying the generic argument
   |
91 |     let chrome = CANIUSE_BROWSERS.get::<Q>(&"chrome".into()).unwrap();
   |                                      +++++
```

I think this was caused by https://github.com/servo/string-cache/pull/266, reverting to 0.8.4 fixes the error

**Comment by YoniFeng** [comment]
Can confirm, I've been looking at the same the same issue wanting to bump string_cache for swc - https://github.com/swc-project/swc/pull/6980

**Comment by realtimetodie** [comment]
0.8.5 needs to be yanked @mrobinson

**Comment by realtimetodie** [comment]
Blocked

- https://github.com/swc-project/swc/pull/6973

**Comment by mrobinson** [comment]
0.8.5 is now yanked.

**Comment by realtimetodie** [comment]
Thank you
