### ISSUE TITLE
0.7.4 no longer builds with rustc 1.34.2

### ISSUE THREAD

**Issue by teythoon** [servo/string-cache#234]
0.7.4 no longer builds with rustc 1.34.2, notably distributed with Debian Buster:

```
error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /home/teythoon/.cargo/registry/src/github.com-1ecc6299db9ec823/string_cache-0.7.4/src/atom.rs:506:26
    |
506 |         let mut buffer = mem::MaybeUninit::<[u8; 64]>::uninit();
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no function or associated item named `uninit` found for type `std::mem::MaybeUninit<[u8; 64]>` in the current scope
   --> /home/teythoon/.cargo/registry/src/github.com-1ecc6299db9ec823/string_cache-0.7.4/src/atom.rs:506:56
    |
506 |         let mut buffer = mem::MaybeUninit::<[u8; 64]>::uninit();
    |                          ------------------------------^^^^^^
    |                          |
    |                          function or associated item not found in `std::mem::MaybeUninit<[u8; 64]>`

error: aborting due to 2 previous errors
```

This is annoying, because a patch-level update introduced a dependency on a newer compiler, creating problems with the `cargo update` and `cargo publish` workflows for anyone using Debian Buster.  Please publish a version 0.7.5 with the offending change reverted.

**Comment by SimonSapin** [comment]
We only recently started testing a fixed Rust version (1.36.0, the first with `MaybeUninit`) on CI for this repository. 0.8.0 is already out, so I’v started a [`v0.7.x`](https://github.com/servo/string-cache/tree/v0.7.x) branch that [tests](https://travis-ci.com/servo/string-cache/builds/133828367) with Rust 1.31.0 and published https://crates.io/crates/string-cache/0.7.5.

**Comment by teythoon** [comment]
Thank you very much, works like a charm :)
